# Generated by Django 3.2.7 on 2021-09-29 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet',
            name='oddspicked',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
