# Generated by Django 3.2.7 on 2021-09-16 05:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_One_Name', models.CharField(max_length=50)),
                ('team_Two_Name', models.CharField(max_length=50)),
                ('team_One_Spread', models.IntegerField()),
                ('team_Two_Spread', models.IntegerField()),
                ('team_One_ML', models.IntegerField()),
                ('team_Two_ML', models.IntegerField()),
                ('over_under', models.IntegerField()),
                ('gameDay', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
