# Generated by Django 3.2.7 on 2021-09-16 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_auto_20210916_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='away_Team_Spread',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='game',
            name='home_Team_Spread',
            field=models.FloatField(),
        ),
    ]
