# Generated by Django 3.2.7 on 2021-10-06 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_auto_20210916_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='away_Team_ML',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='game',
            name='home_Team_ML',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='game',
            name='over_under',
            field=models.FloatField(),
        ),
    ]
